language: c
sudo: false
dist: trusty
services:
  - docker
git:
  depth: 1
env:
  global:
  - DEST_DIR="${HOME}/FTL"
matrix:
  include:
  - env:
    - BUILD_CC="cc"
    - BIN_NAME="pihole-FTL-linux-x86_64"
    addons:
      apt:
        packages:
        - sqlite3
  - env:
    - BUILD_CC="arm-linux-gnueabihf-gcc"
    - BIN_NAME="pihole-FTL-arm-linux-gnueabihf"
    addons:
      apt:
        packages:
        - gcc-arm-linux-gnueabihf
        - binutils-arm-linux-gnueabihf
        - libc6-dev-armhf-cross
  - env:
    - BUILD_CC="arm-linux-gnueabi-gcc"
    - BIN_NAME="pihole-FTL-arm-linux-gnueabi"
    addons:
      apt:
        packages:
        - gcc-arm-linux-gnueabi
        - binutils-arm-linux-gnueabi
        - libc6-dev-armel-cross
  - env:
    - BUILD_CC="aarch64-linux-gnu-gcc"
    - BIN_NAME="pihole-FTL-aarch64-linux-gnu"
    addons:
      apt:
        packages:
        - gcc-aarch64-linux-gnu
        - binutils-aarch64-linux-gnu
        - libc6-dev-arm64-cross
  - env:
    - BUILD_CC="powerpc-linux-gnu-gcc"
    - BIN_NAME="pihole-FTL-powerpc-linux-gnu"
    addons:
      apt:
        packages:
        - gcc-powerpc-linux-gnu
        - binutils-powerpc-linux-gnu
        - libc6-dev-powerpc-cross
  - env:
    - BUILD_CC="cc"
    - CFLAGS="-m32"
    - BIN_NAME="pihole-FTL-linux-x86_32"
    addons:
      apt:
        packages:
        - gcc-multilib
  - env:
    - BUILD_CC="musl-gcc"
    - BIN_NAME="pihole-FTL-musl-linux-x86_64"
    addons:
      apt:
        packages:
        - musl-tools
  - env:
    - BUILD_CC="musl-gcc"
    - BIN_NAME="pihole-FTL-musl-armhf"
    - DOCKER="docker-compose run armhf"
    sudo: true
    install:
      - sudo pip install docker-compose
before_script:
- mkdir -p "${DEST_DIR}"
- make clean
script:
- $DOCKER make pihole-FTL CC="${BUILD_CC}" CFLAGS="${CFLAGS}"
- file pihole-FTL
- if [[ "${BIN_NAME}" == "pihole-FTL-linux-x86_64" ]]; then test/run.sh; fi
- mv pihole-FTL "${DEST_DIR}/${BIN_NAME}"
- cd "${DEST_DIR}"
- sha1sum pihole-FTL-* > ${BIN_NAME}.sha1
- ls -lah "${DEST_DIR}"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: bfCffM3mjXQVjFW8e4qQeaidliDwkjpAEYEqPrU58Y1qpU4M0w5xqjI0mLPquUxzhP5RUTdiuM6UI7jtpNtz3k4L9XNXk7fJADaS+CgWcl1wagNeuHD8VZOZMG0vhzYNOKpLVXHXq+viKGemK20PIooIwpdZdyODhYE7enDJM2h43CHP5hQdBPN63Hx4mfo+d/HLx0OP4i01CdQhXGWA0krTbPOlYSx6hW0D1usEv+tBNCZhb4JhxfiAIjY7r07YokKxtRaJZunufCKBWIp5OUX5WOhbd3UQavB0+5knM4WafkzVmmjHTn/2TYymxID0wyQInf6gIgUNBBke5IeA3/cPVrSwy4vOzB7+2CoPGLBSG8NuQTMa8jfmeo3bz2QvXYwOxY3OrZoPVeo1tU+q441dIIdmeqP0fbW0sU8OLjkOq9ISSDmdhWwUTUeL6puoM4npZprLra284pzSNu4aC90oDN4YREF1UqOxdG3jb4suj9tXX8eQyLkyMvJ0SYVhqT7w+CmQWYlZ5rKV6FLv2PK5cWtVSDctTV9v9+8pwj+JkPe0Q1C1OtWTysVJP+QwI620E8fQG9Jve3hx0sedPg/2VrjG1Ketq3Dnpx5Q5gbnCEqcRkW/yDv1IxTBCjXHo9J0MGY29t5+b+nr8jAVqEPvgT7MyFEiixImtPX54u0=
  file: "${DEST_DIR}/*"
  file_glob: true
  on:
    repo: pi-hole/FTL
    tags: true
