name: Codespell
on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  spell-check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout repository
      uses: actions/checkout@v4.1.2
    -
      name: Spell-Checking
      uses: codespell-project/actions-codespell@master
      with:
        ignore_words_file: .github/.codespellignore
        skip: ./src/database/sqlite3.c,./src/database/sqlite3.h,./src/database/shell.c,./src/lua,./src/dnsmasq,./src/tre-regex,./.git,./test/libs,./src/webserver/civetweb,./src/zip/miniz,./src/api/docs/content/external
        exclude_file: .github/.codespellignore_lines
